version: "3"
services:
  djangoapp:
    container_name: samuel_webscraping_djangoapp
    build:
      context: djangoapp
      dockerfile: Dockerfile
    ports:
      - "${DJANGOAPP_PORT}:8000"
    volumes:
      - ./djangoapp:/usr/src/app
    command: python3 app/manage.py runserver 0.0.0.0:8000
